### ISSUE TITLE
Problem when loading Movements - KeyError: 'oid' 

### ISSUE THREAD

**Issue by sstromat** [eurocontrol-asu/open_alaqs#176]
Not exactly sure what's wrong here, but I cannot load the movements any more:
```
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 175, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
KeyError: 'oid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\openalaqsdialog.py", line 2559, in source_type_changed
    mod_ = EmissionSourceModule(em_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\core\modules\MovementSourceModule.py", line 49, in __init__
    movement_store = MovementStore(self.getDatabasePath())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\core\tools\Singleton.py", line 14, in __call__
    cls.instance = super(Singleton, cls).__call__(*args, **kw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\core\interfaces\Movement.py", line 2001, in __init__
    self.initMovements(debug)
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\core\interfaces\Movement.py", line 2271, in initMovements
    mdf[none_profile_ids].apply(
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sstromat\dev\qgis\profiles\default/python/plugins\open_alaqs\core\interfaces\Movement.py", line 2273, in 
    f"Skip movement {row['oid']} due to nor profile {row['profile_id']} nor default value"
                     ~~~^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'oid'
```

**Comment by suricactus** [comment]
I am pretty sure this is no longer an issue, closing.
